### ISSUE TITLE
User Locked for failed attempt is not working

### ISSUE THREAD

**Issue by ratagupt** [openbmc/phosphor-user-manager#2]
@rthomaiy Seems that user locked for the failed attempt is not working, I tried to do the ssh to the with invalid credentials but it doesn't lock the user.
However, I checked that pam_tally gets the failure count but it doesn't lock the user account.
Seems we need to add the pam_failock in the pam configuration file(common-auth and common-account) for locking the user.

Before running the above test(ssh with 4 failure attempts) I set the MaxLoginAttemptBeforeLockout to "3" which is in account policy interface.

**Comment by rthomaiy** [comment]
I tried the same and it works fine. Are you trying for root user. Because, we won't lock out the root user, and if we need to do same for root user, then even_deny_root options has to be used. But it will also cause other issues like DOS attacks
Note: Ultimately, we need to remove the root user, and user id 1 etc, has to be created through Host interface or any other logic, that's the direction we are marching towards. Let me know, if you still see any problem.

**Comment by ratagupt** [comment]
@rthomaiy:- I was trying to lock nonroot user, Can you get me the cmds which you used?

**Comment by rthomaiy** [comment]
executed below command and tried to do a ssh, using the ipmi created user @ user id 2(in my case it was newuser), tried giving 3 failed attempts to the ssh password (login: testuser) and after 4the attempt even if i try to give correct password it will not allow to login (Note: verified ssh was able to establish with correct password, before proceeding with the test, and the lockout, if i clear the lockout, then will be able to login again)
busctl set-property xyz.openbmc_project.User.Manager /xyz/openbmc_project/user xyz.openbmc_project.User.AccountPolicy MaxLoginAttemptBeforeLockout q 3

Output sample: 
login as: newuser
newuser@xx.xx.xx.xx's password:
Access denied
newuser@xx.xx.xx.xx's password:
Access denied
newuser@xx.xx.xx.xx's password:
Access denied
newuser@xx.xx.xx.xx's password:

Account locked due to 4 failed logins
Access denied
newuser@xx.xx.xx.xx's password:


(Note: In case if you are still facing the problem, can you dump /etc/pam.d/common-auth and see whether entry deny= is listed for pam_tally2

**Comment by ratagupt** [comment]
oops I was using the following cmd to check the user lock failure count 
pam_tally2 -u username -r
-r causes resets the failure count, that is the reason user were not getting locked out.

Closing this issue as it is working.
